#!/bin/sh
# hint: make an alias wih the argument built-in for quickly deploying the tail -f script here
FILTER=.filter
IRCTOPLEVEL="$1"
LINES=${2:-5}
#cd "$1" ; tail -f -n $LINES $(find "$1" -name out | grep \#) | ./.filter
cd "$1"
# Create temp file for file list to avoid subshell
tempfile=$(mktemp)

# Clean up all tail processes and temp file on exit/CTRL-C  
trap 'pkill -f "tail -F.*$1.*out"; rm -f "$tempfile"; exit' INT

find "$1" -name out | grep "#" | sort > "$tempfile"

while read file; do
    channel=$(echo "$file" | sed 's/.*\/\(#[^\/]*\)\/out$/\1/')
    # Generate color based on channel name hash using sum of all characters (mod to keep number small)
    hash=$(printf "%s" "$channel" | od -b | awk '{for(i=2;i<=NF;i++) s=(s+$i)%1000} END{print s+0}')
    color=$((31 + hash % 6))
    (tail -F -n $LINES "$file" | ./"$FILTER" | sed -u 's/\x1b\[[0-9;]*m//g' | sed -u "s/^/\x1b[${color}m[$channel]\x1b[0m\t/" | stdbuf -o0 cat) &
done < "$tempfile"

rm "$tempfile"
wait
