#!/bin/sh

WAIT=5

# IRC client connector script
# Usage: irc-connect <server> <nick> <pass> <dir> [channel1] [channel2] ...

SERVER="$1"
NICK="$2"
PASS="$3"
DIR="$4"
shift 4

ii -s "$SERVER" -n "$NICK" -i "$DIR" -e &
II_PID=$!
sleep "$WAIT"

echo "/msg NickServ IDENTIFY $NICK $PASS" >"$DIR"/"$SERVER"/in || echo "IDENTIFY $NICK $PASS" >"$DIR"/"$SERVER"/nickserv/in 

sleep $WAIT

# Join all provided channels
for channel in "$@"; do
    echo "/j $channel" >"$DIR"/"$SERVER"/in
    sleep "$WAIT"
done

wait $II_PID
