#!/bin/sh

# Usage: lchat-connect <dir> <server> <channel>

DIR="$1"
SERVER="$2"
CHANNEL="$3"

# KLUDGE: why does lchat work like this!
#
echo "#!/bin/sh\nsed '/ -!- /d'" >.filter
chmod +x .filter

trap 'rm -f .filter' EXIT INT TERM

lchat -a "$DIR"/"$SERVER"/"$CHANNEL" -n 50
